-keep class com.gearan.watch.** { *; }
-dontwarn javax.crypto.**
-dontwarn com.google.errorprone.annotations.CanIgnoreReturnValue
-dontwarn com.google.errorprone.annotations.CheckReturnValue
-dontwarn com.google.errorprone.annotations.Immutable
-dontwarn javax.annotation.Nullable
-dontwarn javax.annotation.concurrent.GuardedBy
